# Generated by Django 4.1.7 on 2023-02-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_rouletteowner_roulettewinner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roulette',
            options={'verbose_name': 'Rifa', 'verbose_name_plural': 'Rifas'},
        ),
        migrations.AlterModelOptions(
            name='roulettenumber',
            options={'verbose_name': 'Número da sorte', 'verbose_name_plural': 'Números da sorte'},
        ),
        migrations.AlterModelOptions(
            name='roulettewinner',
            options={'verbose_name': 'Ganhador', 'verbose_name_plural': 'Ganhadoress'},
        ),
        migrations.RenameField(
            model_name='roulettewinner',
            old_name='owner',
            new_name='winner',
        ),
    ]
