# Generated by Django 4.1.7 on 2023-02-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_roulette_options_alter_roulettenumber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roulettewinner',
            name='number',
            field=models.CharField(default='', max_length=50, verbose_name='Número do bilhete premiado'),
        ),
    ]
